version: "2"
services:
  app:
    build:
      context: ./config/docker
      dockerfile: Dockerfile.app
    command: bash
    volumes:
      - .:/trello.md
      - npm-data:/home/opam/.npm
volumes:
  npm-data:
    driver: local
